pluginManagement {
	repositories {
		mavenLocal()

		maven {
			url 'https://repo1.maven.org/maven2/'
			name 'Maven Central Direct'
		}

		maven {
			url 'https://repo.huaweicloud.com/repository/maven/'
			name 'Huawei Mirror'
		}
		maven {
			url 'https://maven.aliyun.com/repository/central'
			name 'Aliyun Central'
		}

		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}